general
{ 
    before_sleep_cmd = uwsm app -- hyprlock # Lock screen before idling
    lock_cmd = pidof hyprlock || uwsm app -- hyprlock # avoid starting multiple hyprlock instances.
    after_sleep_cmd = hyprctl dispatch dpms on # to avoid having to press a key twice to turn on the display.
}

listener
{
    timeout = 150 # 2.5min.
    on-timeout = brightnessctl -s set 10 # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r # monitor backlight restore. 
}

listener
{
    timeout = 270 # 4.5min.
    on-timeout = notify-send "Idling in 30s" # command to run when timeout has passed.
}

listener
{
    timeout = 300 # 5min.
    on-timeout = loginctl lock-session # Lock Screen
}

listener
{
    timeout = 330 # 5.5min.
    on-timeout = hyprctl dispatch dpms off # screen off 30 seconds after idling
    on-resume = hyprctl dispatch dpms on # Turn the screen on when activity detected
}

listener
{
    timeout = 600 # 10min.
    on-timeout = systemctl suspend # Suspend system
} 